---
# tasks file for postgresql
- debug:
    msg: "Azure PostgreSQL: name: {{ meta.name }}, {{ meta.namespace }}"

- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    state: "{{ state }}"
  register: rg
  when: state == "present" 
# ^^^^ Lets not delete the resource group

- debug:
    var: rg


- name: Create PostgreSQL Server
  azure_rm_postgresqlserver:
    resource_group: "{{ resource_group }}"
    name: "{{ postgresqlserver_name }}"
    sku:
      name: B_Gen5_1
      tier: Basic
      capacity: 1
    location: "{{ location }}"
    enforce_ssl: True
    admin_username: "{{ admin_username }}"
    admin_password: "{{ admin_password }}"
    storage_mb: 51200
    state: "{{ state }}"
  register: pgs

- debug:
    var: pgs

- name: Create instance of PostgreSQL Database
  azure_rm_postgresqldatabase:
    resource_group: "{{ resource_group }}"
    server_name: "{{ postgresqlserver_name }}"
    name: "{{ postgresqldb_name }}"
    state: "{{ state }}"
  register: pgdb

- debug:
    var: pgdb

- k8s_status:
    api_version: aso.example.org/v1alpha1
    kind: Postgresql
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    status:
      whoami: "Namespace{{ meta.namespace }} - Name: {{ meta.name }}"
      fully_qualified_domain_name: "{{pgs.fully_qualified_domain_name | default('na')}}"
      postgresqldb_name: "{{ postgresqldb_name | default('na') }} "


