apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: azure-service-operator-catalog
spec:
  sourceType: grpc
  image: quay.io/sbergste/azure-service-operator-index:v0.0.1
  displayName: Azure Service Operator Catalog
  publisher: StefanB


