apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: azure-service-operators
spec:

  displayName: Azure Service Operators
  endpoint: https://quay.io/cnr
  publisher: StefanB

  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: sbergste