apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.aso.example.org
spec:
  group: aso.example.org
  names:
    kind: Postgresql
    listKind: PostgresqlList
    plural: postgresqls
    singular: postgresql
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true


